'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace Oca
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="#Oca_Express_Pak", ConfigurationName:="Oca.Oep_TrackingSoap")>  _
    Public Interface Oep_TrackingSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/List_Envios", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function List_Envios(ByVal CUIT As String, ByVal FechaDesde As String, ByVal FechaHasta As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/List_Envios", ReplyAction:="*")>  _
        Function List_EnviosAsync(ByVal CUIT As String, ByVal FechaDesde As String, ByVal FechaHasta As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/Tracking_Pieza", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Tracking_Pieza(ByVal NroDocumentoCliente As String, ByVal CUIT As String, ByVal Pieza As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/Tracking_Pieza", ReplyAction:="*")>  _
        Function Tracking_PiezaAsync(ByVal NroDocumentoCliente As String, ByVal CUIT As String, ByVal Pieza As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/Tracking_OrdenRetiro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Tracking_OrdenRetiro(ByVal CUIT As String, ByVal OrdenRetiro As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/Tracking_OrdenRetiro", ReplyAction:="*")>  _
        Function Tracking_OrdenRetiroAsync(ByVal CUIT As String, ByVal OrdenRetiro As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/Tarifar_Envio_Corporativo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Tarifar_Envio_Corporativo(ByVal PesoTotal As String, ByVal VolumenTotal As String, ByVal CodigoPostalOrigen As Integer, ByVal CodigoPostalDestino As Integer, ByVal CantidadPaquetes As Long, ByVal Cuit As String, ByVal Operativa As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/Tarifar_Envio_Corporativo", ReplyAction:="*")>  _
        Function Tarifar_Envio_CorporativoAsync(ByVal PesoTotal As String, ByVal VolumenTotal As String, ByVal CodigoPostalOrigen As Integer, ByVal CodigoPostalDestino As Integer, ByVal CantidadPaquetes As Long, ByVal Cuit As String, ByVal Operativa As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/AnularOrdenGenerada", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function AnularOrdenGenerada(ByVal usuario As String, ByVal password As String, ByVal nroOrden As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/AnularOrdenGenerada", ReplyAction:="*")>  _
        Function AnularOrdenGeneradaAsync(ByVal usuario As String, ByVal password As String, ByVal nroOrden As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GenerarConsolidacionDeOrdenesDeRetiro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GenerarConsolidacionDeOrdenesDeRetiro(ByVal usr As String, ByVal psw As String, ByVal ordenesDeRetiro As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GenerarConsolidacionDeOrdenesDeRetiro", ReplyAction:="*")>  _
        Function GenerarConsolidacionDeOrdenesDeRetiroAsync(ByVal usr As String, ByVal psw As String, ByVal ordenesDeRetiro As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetEnviosUltimoEstado", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetEnviosUltimoEstado(ByVal cuit As String, ByVal operativas() As String, ByVal fechaDesde As Date, ByVal fechaHasta As Date) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetEnviosUltimoEstado", ReplyAction:="*")>  _
        Function GetEnviosUltimoEstadoAsync(ByVal cuit As String, ByVal operativas() As String, ByVal fechaDesde As Date, ByVal fechaHasta As Date) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GenerateQrByOrdenDeRetiro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GenerateQrByOrdenDeRetiro(ByVal usr As String, ByVal psw As String, ByVal idOrdenDeRetiro As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GenerateQrByOrdenDeRetiro", ReplyAction:="*")>  _
        Function GenerateQrByOrdenDeRetiroAsync(ByVal usr As String, ByVal psw As String, ByVal idOrdenDeRetiro As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GenerateQRParaPaquetes", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GenerateQRParaPaquetes(ByVal usr As String, ByVal psw As String, ByVal numeroDeEnvio As String, ByVal idpaquete As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GenerateQRParaPaquetes", ReplyAction:="*")>  _
        Function GenerateQRParaPaquetesAsync(ByVal usr As String, ByVal psw As String, ByVal numeroDeEnvio As String, ByVal idpaquete As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GenerateListQrPorEnvio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GenerateListQrPorEnvio(ByVal usr As String, ByVal psw As String, ByVal numeroDeEnvio As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GenerateListQrPorEnvio", ReplyAction:="*")>  _
        Function GenerateListQrPorEnvioAsync(ByVal usr As String, ByVal psw As String, ByVal numeroDeEnvio As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/IngresoOR", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function IngresoOR(ByVal usr As String, ByVal psw As String, ByVal XML_Retiro As String, ByVal ConfirmarRetiro As Boolean, ByVal DiasRetiro As Integer, ByVal FranjaHoraria As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/IngresoOR", ReplyAction:="*")>  _
        Function IngresoORAsync(ByVal usr As String, ByVal psw As String, ByVal XML_Retiro As String, ByVal ConfirmarRetiro As Boolean, ByVal DiasRetiro As Integer, ByVal FranjaHoraria As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentroCostoPorOperativa", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCentroCostoPorOperativa(ByVal CUIT As String, ByVal Operativa As Integer) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentroCostoPorOperativa", ReplyAction:="*")>  _
        Function GetCentroCostoPorOperativaAsync(ByVal CUIT As String, ByVal Operativa As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentrosImposicion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCentrosImposicion() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentrosImposicion", ReplyAction:="*")>  _
        Function GetCentrosImposicionAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetELockerOCA", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetELockerOCA() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetELockerOCA", ReplyAction:="*")>  _
        Function GetELockerOCAAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentrosImposicionAdmision", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCentrosImposicionAdmision() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentrosImposicionAdmision", ReplyAction:="*")>  _
        Function GetCentrosImposicionAdmisionAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetServiciosDeCentrosImposicion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetServiciosDeCentrosImposicion() As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetServiciosDeCentrosImposicion", ReplyAction:="*")>  _
        Function GetServiciosDeCentrosImposicionAsync() As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/TrackingEnvio_EstadoActual", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function TrackingEnvio_EstadoActual(ByVal numeroEnvio As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/TrackingEnvio_EstadoActual", ReplyAction:="*")>  _
        Function TrackingEnvio_EstadoActualAsync(ByVal numeroEnvio As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetProvincias", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetProvincias() As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetProvincias", ReplyAction:="*")>  _
        Function GetProvinciasAsync() As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetLocalidadesByProvincia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetLocalidadesByProvincia(ByVal idProvincia As Integer) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetLocalidadesByProvincia", ReplyAction:="*")>  _
        Function GetLocalidadesByProvinciaAsync(ByVal idProvincia As Integer) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetServiciosDeCentrosImposicion_xProvincia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetServiciosDeCentrosImposicion_xProvincia(ByVal provinciaID As Integer, ByVal localidad As String) As System.Xml.XmlNode
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetServiciosDeCentrosImposicion_xProvincia", ReplyAction:="*")>  _
        Function GetServiciosDeCentrosImposicion_xProvinciaAsync(ByVal provinciaID As Integer, ByVal localidad As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentrosImposicionPorCP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCentrosImposicionPorCP(ByVal CodigoPostal As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentrosImposicionPorCP", ReplyAction:="*")>  _
        Function GetCentrosImposicionPorCPAsync(ByVal CodigoPostal As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentrosImposicionAdmisionPorCP", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCentrosImposicionAdmisionPorCP(ByVal CodigoPostal As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetCentrosImposicionAdmisionPorCP", ReplyAction:="*")>  _
        Function GetCentrosImposicionAdmisionPorCPAsync(ByVal CodigoPostal As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetHtmlDeEtiquetasPorOrdenOrNumeroEnvio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetHtmlDeEtiquetasPorOrdenOrNumeroEnvio(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetHtmlDeEtiquetasPorOrdenOrNumeroEnvio", ReplyAction:="*")>  _
        Function GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadora", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadora(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadora", ReplyAction:="*")>  _
        Function GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadoraAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetDatosDeEtiquetasPorOrdenOrNumeroEnvio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetDatosDeEtiquetasPorOrdenOrNumeroEnvio(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String, ByVal isLocker As Boolean) As Oca.Etiqueta()
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetDatosDeEtiquetasPorOrdenOrNumeroEnvio", ReplyAction:="*")>  _
        Function GetDatosDeEtiquetasPorOrdenOrNumeroEnvioAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String, ByVal isLocker As Boolean) As System.Threading.Tasks.Task(Of Oca.Etiqueta())
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvio(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvio", ReplyAction:="*")>  _
        Function GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadora", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadora(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadora", ReplyAction:="*")>  _
        Function GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadoraAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetPdfDeEtiquetasPorOrdenOrNumeroEnvio", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetPdfDeEtiquetasPorOrdenOrNumeroEnvio(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String, ByVal logisticaInversa As Boolean) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="#Oca_Express_Pak/GetPdfDeEtiquetasPorOrdenOrNumeroEnvio", ReplyAction:="*")>  _
        Function GetPdfDeEtiquetasPorOrdenOrNumeroEnvioAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String, ByVal logisticaInversa As Boolean) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="#Oca_Express_Pak")>  _
    Partial Public Class Etiqueta
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nroOrdenField As String
        
        Private nroGuiaField As String
        
        Private docClienteField As String
        
        Private servicioField As String
        
        Private bultoField As String
        
        Private operativaField As String
        
        Private pesoTotalField As String
        
        Private sucursalDestinoField As String
        
        Private sucursalOrigenField As String
        
        Private sucursalGuardaField As String
        
        Private entregaField As String
        
        Private destinatarioField As String
        
        Private domicilioField As String
        
        Private telefonoField As String
        
        Private remitenteField As String
        
        Private observacionesField As String
        
        Private codigoAperturaField As String
        
        Private qrField As String
        
        Private codeBarField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property NroOrden() As String
            Get
                Return Me.nroOrdenField
            End Get
            Set
                Me.nroOrdenField = value
                Me.RaisePropertyChanged("NroOrden")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property NroGuia() As String
            Get
                Return Me.nroGuiaField
            End Get
            Set
                Me.nroGuiaField = value
                Me.RaisePropertyChanged("NroGuia")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property DocCliente() As String
            Get
                Return Me.docClienteField
            End Get
            Set
                Me.docClienteField = value
                Me.RaisePropertyChanged("DocCliente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Servicio() As String
            Get
                Return Me.servicioField
            End Get
            Set
                Me.servicioField = value
                Me.RaisePropertyChanged("Servicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Bulto() As String
            Get
                Return Me.bultoField
            End Get
            Set
                Me.bultoField = value
                Me.RaisePropertyChanged("Bulto")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Operativa() As String
            Get
                Return Me.operativaField
            End Get
            Set
                Me.operativaField = value
                Me.RaisePropertyChanged("Operativa")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property PesoTotal() As String
            Get
                Return Me.pesoTotalField
            End Get
            Set
                Me.pesoTotalField = value
                Me.RaisePropertyChanged("PesoTotal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property SucursalDestino() As String
            Get
                Return Me.sucursalDestinoField
            End Get
            Set
                Me.sucursalDestinoField = value
                Me.RaisePropertyChanged("SucursalDestino")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property SucursalOrigen() As String
            Get
                Return Me.sucursalOrigenField
            End Get
            Set
                Me.sucursalOrigenField = value
                Me.RaisePropertyChanged("SucursalOrigen")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property SucursalGuarda() As String
            Get
                Return Me.sucursalGuardaField
            End Get
            Set
                Me.sucursalGuardaField = value
                Me.RaisePropertyChanged("SucursalGuarda")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Entrega() As String
            Get
                Return Me.entregaField
            End Get
            Set
                Me.entregaField = value
                Me.RaisePropertyChanged("Entrega")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property Destinatario() As String
            Get
                Return Me.destinatarioField
            End Get
            Set
                Me.destinatarioField = value
                Me.RaisePropertyChanged("Destinatario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property Domicilio() As String
            Get
                Return Me.domicilioField
            End Get
            Set
                Me.domicilioField = value
                Me.RaisePropertyChanged("Domicilio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property Telefono() As String
            Get
                Return Me.telefonoField
            End Get
            Set
                Me.telefonoField = value
                Me.RaisePropertyChanged("Telefono")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property Remitente() As String
            Get
                Return Me.remitenteField
            End Get
            Set
                Me.remitenteField = value
                Me.RaisePropertyChanged("Remitente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property Observaciones() As String
            Get
                Return Me.observacionesField
            End Get
            Set
                Me.observacionesField = value
                Me.RaisePropertyChanged("Observaciones")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property CodigoApertura() As String
            Get
                Return Me.codigoAperturaField
            End Get
            Set
                Me.codigoAperturaField = value
                Me.RaisePropertyChanged("CodigoApertura")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property QR() As String
            Get
                Return Me.qrField
            End Get
            Set
                Me.qrField = value
                Me.RaisePropertyChanged("QR")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property CodeBar() As String
            Get
                Return Me.codeBarField
            End Get
            Set
                Me.codeBarField = value
                Me.RaisePropertyChanged("CodeBar")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Oep_TrackingSoapChannel
        Inherits Oca.Oep_TrackingSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Oep_TrackingSoapClient
        Inherits System.ServiceModel.ClientBase(Of Oca.Oep_TrackingSoap)
        Implements Oca.Oep_TrackingSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function List_Envios(ByVal CUIT As String, ByVal FechaDesde As String, ByVal FechaHasta As String) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.List_Envios
            Return MyBase.Channel.List_Envios(CUIT, FechaDesde, FechaHasta)
        End Function
        
        Public Function List_EnviosAsync(ByVal CUIT As String, ByVal FechaDesde As String, ByVal FechaHasta As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.List_EnviosAsync
            Return MyBase.Channel.List_EnviosAsync(CUIT, FechaDesde, FechaHasta)
        End Function
        
        Public Function Tracking_Pieza(ByVal NroDocumentoCliente As String, ByVal CUIT As String, ByVal Pieza As String) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.Tracking_Pieza
            Return MyBase.Channel.Tracking_Pieza(NroDocumentoCliente, CUIT, Pieza)
        End Function
        
        Public Function Tracking_PiezaAsync(ByVal NroDocumentoCliente As String, ByVal CUIT As String, ByVal Pieza As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.Tracking_PiezaAsync
            Return MyBase.Channel.Tracking_PiezaAsync(NroDocumentoCliente, CUIT, Pieza)
        End Function
        
        Public Function Tracking_OrdenRetiro(ByVal CUIT As String, ByVal OrdenRetiro As Integer) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.Tracking_OrdenRetiro
            Return MyBase.Channel.Tracking_OrdenRetiro(CUIT, OrdenRetiro)
        End Function
        
        Public Function Tracking_OrdenRetiroAsync(ByVal CUIT As String, ByVal OrdenRetiro As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.Tracking_OrdenRetiroAsync
            Return MyBase.Channel.Tracking_OrdenRetiroAsync(CUIT, OrdenRetiro)
        End Function
        
        Public Function Tarifar_Envio_Corporativo(ByVal PesoTotal As String, ByVal VolumenTotal As String, ByVal CodigoPostalOrigen As Integer, ByVal CodigoPostalDestino As Integer, ByVal CantidadPaquetes As Long, ByVal Cuit As String, ByVal Operativa As String) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.Tarifar_Envio_Corporativo
            Return MyBase.Channel.Tarifar_Envio_Corporativo(PesoTotal, VolumenTotal, CodigoPostalOrigen, CodigoPostalDestino, CantidadPaquetes, Cuit, Operativa)
        End Function
        
        Public Function Tarifar_Envio_CorporativoAsync(ByVal PesoTotal As String, ByVal VolumenTotal As String, ByVal CodigoPostalOrigen As Integer, ByVal CodigoPostalDestino As Integer, ByVal CantidadPaquetes As Long, ByVal Cuit As String, ByVal Operativa As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.Tarifar_Envio_CorporativoAsync
            Return MyBase.Channel.Tarifar_Envio_CorporativoAsync(PesoTotal, VolumenTotal, CodigoPostalOrigen, CodigoPostalDestino, CantidadPaquetes, Cuit, Operativa)
        End Function
        
        Public Function AnularOrdenGenerada(ByVal usuario As String, ByVal password As String, ByVal nroOrden As Integer) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.AnularOrdenGenerada
            Return MyBase.Channel.AnularOrdenGenerada(usuario, password, nroOrden)
        End Function
        
        Public Function AnularOrdenGeneradaAsync(ByVal usuario As String, ByVal password As String, ByVal nroOrden As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.AnularOrdenGeneradaAsync
            Return MyBase.Channel.AnularOrdenGeneradaAsync(usuario, password, nroOrden)
        End Function
        
        Public Function GenerarConsolidacionDeOrdenesDeRetiro(ByVal usr As String, ByVal psw As String, ByVal ordenesDeRetiro As String) As String Implements Oca.Oep_TrackingSoap.GenerarConsolidacionDeOrdenesDeRetiro
            Return MyBase.Channel.GenerarConsolidacionDeOrdenesDeRetiro(usr, psw, ordenesDeRetiro)
        End Function
        
        Public Function GenerarConsolidacionDeOrdenesDeRetiroAsync(ByVal usr As String, ByVal psw As String, ByVal ordenesDeRetiro As String) As System.Threading.Tasks.Task(Of String) Implements Oca.Oep_TrackingSoap.GenerarConsolidacionDeOrdenesDeRetiroAsync
            Return MyBase.Channel.GenerarConsolidacionDeOrdenesDeRetiroAsync(usr, psw, ordenesDeRetiro)
        End Function
        
        Public Function GetEnviosUltimoEstado(ByVal cuit As String, ByVal operativas() As String, ByVal fechaDesde As Date, ByVal fechaHasta As Date) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.GetEnviosUltimoEstado
            Return MyBase.Channel.GetEnviosUltimoEstado(cuit, operativas, fechaDesde, fechaHasta)
        End Function
        
        Public Function GetEnviosUltimoEstadoAsync(ByVal cuit As String, ByVal operativas() As String, ByVal fechaDesde As Date, ByVal fechaHasta As Date) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.GetEnviosUltimoEstadoAsync
            Return MyBase.Channel.GetEnviosUltimoEstadoAsync(cuit, operativas, fechaDesde, fechaHasta)
        End Function
        
        Public Function GenerateQrByOrdenDeRetiro(ByVal usr As String, ByVal psw As String, ByVal idOrdenDeRetiro As String) As String Implements Oca.Oep_TrackingSoap.GenerateQrByOrdenDeRetiro
            Return MyBase.Channel.GenerateQrByOrdenDeRetiro(usr, psw, idOrdenDeRetiro)
        End Function
        
        Public Function GenerateQrByOrdenDeRetiroAsync(ByVal usr As String, ByVal psw As String, ByVal idOrdenDeRetiro As String) As System.Threading.Tasks.Task(Of String) Implements Oca.Oep_TrackingSoap.GenerateQrByOrdenDeRetiroAsync
            Return MyBase.Channel.GenerateQrByOrdenDeRetiroAsync(usr, psw, idOrdenDeRetiro)
        End Function
        
        Public Function GenerateQRParaPaquetes(ByVal usr As String, ByVal psw As String, ByVal numeroDeEnvio As String, ByVal idpaquete As String) As String Implements Oca.Oep_TrackingSoap.GenerateQRParaPaquetes
            Return MyBase.Channel.GenerateQRParaPaquetes(usr, psw, numeroDeEnvio, idpaquete)
        End Function
        
        Public Function GenerateQRParaPaquetesAsync(ByVal usr As String, ByVal psw As String, ByVal numeroDeEnvio As String, ByVal idpaquete As String) As System.Threading.Tasks.Task(Of String) Implements Oca.Oep_TrackingSoap.GenerateQRParaPaquetesAsync
            Return MyBase.Channel.GenerateQRParaPaquetesAsync(usr, psw, numeroDeEnvio, idpaquete)
        End Function
        
        Public Function GenerateListQrPorEnvio(ByVal usr As String, ByVal psw As String, ByVal numeroDeEnvio As String) As String() Implements Oca.Oep_TrackingSoap.GenerateListQrPorEnvio
            Return MyBase.Channel.GenerateListQrPorEnvio(usr, psw, numeroDeEnvio)
        End Function
        
        Public Function GenerateListQrPorEnvioAsync(ByVal usr As String, ByVal psw As String, ByVal numeroDeEnvio As String) As System.Threading.Tasks.Task(Of String()) Implements Oca.Oep_TrackingSoap.GenerateListQrPorEnvioAsync
            Return MyBase.Channel.GenerateListQrPorEnvioAsync(usr, psw, numeroDeEnvio)
        End Function
        
        Public Function IngresoOR(ByVal usr As String, ByVal psw As String, ByVal XML_Retiro As String, ByVal ConfirmarRetiro As Boolean, ByVal DiasRetiro As Integer, ByVal FranjaHoraria As Integer) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.IngresoOR
            Return MyBase.Channel.IngresoOR(usr, psw, XML_Retiro, ConfirmarRetiro, DiasRetiro, FranjaHoraria)
        End Function
        
        Public Function IngresoORAsync(ByVal usr As String, ByVal psw As String, ByVal XML_Retiro As String, ByVal ConfirmarRetiro As Boolean, ByVal DiasRetiro As Integer, ByVal FranjaHoraria As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.IngresoORAsync
            Return MyBase.Channel.IngresoORAsync(usr, psw, XML_Retiro, ConfirmarRetiro, DiasRetiro, FranjaHoraria)
        End Function
        
        Public Function GetCentroCostoPorOperativa(ByVal CUIT As String, ByVal Operativa As Integer) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.GetCentroCostoPorOperativa
            Return MyBase.Channel.GetCentroCostoPorOperativa(CUIT, Operativa)
        End Function
        
        Public Function GetCentroCostoPorOperativaAsync(ByVal CUIT As String, ByVal Operativa As Integer) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.GetCentroCostoPorOperativaAsync
            Return MyBase.Channel.GetCentroCostoPorOperativaAsync(CUIT, Operativa)
        End Function
        
        Public Function GetCentrosImposicion() As System.Data.DataSet Implements Oca.Oep_TrackingSoap.GetCentrosImposicion
            Return MyBase.Channel.GetCentrosImposicion
        End Function
        
        Public Function GetCentrosImposicionAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.GetCentrosImposicionAsync
            Return MyBase.Channel.GetCentrosImposicionAsync
        End Function
        
        Public Function GetELockerOCA() As System.Data.DataSet Implements Oca.Oep_TrackingSoap.GetELockerOCA
            Return MyBase.Channel.GetELockerOCA
        End Function
        
        Public Function GetELockerOCAAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.GetELockerOCAAsync
            Return MyBase.Channel.GetELockerOCAAsync
        End Function
        
        Public Function GetCentrosImposicionAdmision() As System.Data.DataSet Implements Oca.Oep_TrackingSoap.GetCentrosImposicionAdmision
            Return MyBase.Channel.GetCentrosImposicionAdmision
        End Function
        
        Public Function GetCentrosImposicionAdmisionAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.GetCentrosImposicionAdmisionAsync
            Return MyBase.Channel.GetCentrosImposicionAdmisionAsync
        End Function
        
        Public Function GetServiciosDeCentrosImposicion() As System.Xml.XmlNode Implements Oca.Oep_TrackingSoap.GetServiciosDeCentrosImposicion
            Return MyBase.Channel.GetServiciosDeCentrosImposicion
        End Function
        
        Public Function GetServiciosDeCentrosImposicionAsync() As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements Oca.Oep_TrackingSoap.GetServiciosDeCentrosImposicionAsync
            Return MyBase.Channel.GetServiciosDeCentrosImposicionAsync
        End Function
        
        Public Function TrackingEnvio_EstadoActual(ByVal numeroEnvio As String) As System.Xml.XmlNode Implements Oca.Oep_TrackingSoap.TrackingEnvio_EstadoActual
            Return MyBase.Channel.TrackingEnvio_EstadoActual(numeroEnvio)
        End Function
        
        Public Function TrackingEnvio_EstadoActualAsync(ByVal numeroEnvio As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements Oca.Oep_TrackingSoap.TrackingEnvio_EstadoActualAsync
            Return MyBase.Channel.TrackingEnvio_EstadoActualAsync(numeroEnvio)
        End Function
        
        Public Function GetProvincias() As System.Xml.XmlNode Implements Oca.Oep_TrackingSoap.GetProvincias
            Return MyBase.Channel.GetProvincias
        End Function
        
        Public Function GetProvinciasAsync() As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements Oca.Oep_TrackingSoap.GetProvinciasAsync
            Return MyBase.Channel.GetProvinciasAsync
        End Function
        
        Public Function GetLocalidadesByProvincia(ByVal idProvincia As Integer) As System.Xml.XmlNode Implements Oca.Oep_TrackingSoap.GetLocalidadesByProvincia
            Return MyBase.Channel.GetLocalidadesByProvincia(idProvincia)
        End Function
        
        Public Function GetLocalidadesByProvinciaAsync(ByVal idProvincia As Integer) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements Oca.Oep_TrackingSoap.GetLocalidadesByProvinciaAsync
            Return MyBase.Channel.GetLocalidadesByProvinciaAsync(idProvincia)
        End Function
        
        Public Function GetServiciosDeCentrosImposicion_xProvincia(ByVal provinciaID As Integer, ByVal localidad As String) As System.Xml.XmlNode Implements Oca.Oep_TrackingSoap.GetServiciosDeCentrosImposicion_xProvincia
            Return MyBase.Channel.GetServiciosDeCentrosImposicion_xProvincia(provinciaID, localidad)
        End Function
        
        Public Function GetServiciosDeCentrosImposicion_xProvinciaAsync(ByVal provinciaID As Integer, ByVal localidad As String) As System.Threading.Tasks.Task(Of System.Xml.XmlNode) Implements Oca.Oep_TrackingSoap.GetServiciosDeCentrosImposicion_xProvinciaAsync
            Return MyBase.Channel.GetServiciosDeCentrosImposicion_xProvinciaAsync(provinciaID, localidad)
        End Function
        
        Public Function GetCentrosImposicionPorCP(ByVal CodigoPostal As String) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.GetCentrosImposicionPorCP
            Return MyBase.Channel.GetCentrosImposicionPorCP(CodigoPostal)
        End Function
        
        Public Function GetCentrosImposicionPorCPAsync(ByVal CodigoPostal As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.GetCentrosImposicionPorCPAsync
            Return MyBase.Channel.GetCentrosImposicionPorCPAsync(CodigoPostal)
        End Function
        
        Public Function GetCentrosImposicionAdmisionPorCP(ByVal CodigoPostal As String) As System.Data.DataSet Implements Oca.Oep_TrackingSoap.GetCentrosImposicionAdmisionPorCP
            Return MyBase.Channel.GetCentrosImposicionAdmisionPorCP(CodigoPostal)
        End Function
        
        Public Function GetCentrosImposicionAdmisionPorCPAsync(ByVal CodigoPostal As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements Oca.Oep_TrackingSoap.GetCentrosImposicionAdmisionPorCPAsync
            Return MyBase.Channel.GetCentrosImposicionAdmisionPorCPAsync(CodigoPostal)
        End Function
        
        Public Function GetHtmlDeEtiquetasPorOrdenOrNumeroEnvio(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As String Implements Oca.Oep_TrackingSoap.GetHtmlDeEtiquetasPorOrdenOrNumeroEnvio
            Return MyBase.Channel.GetHtmlDeEtiquetasPorOrdenOrNumeroEnvio(idOrdenRetiro, nroEnvio)
        End Function
        
        Public Function GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As System.Threading.Tasks.Task(Of String) Implements Oca.Oep_TrackingSoap.GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioAsync
            Return MyBase.Channel.GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioAsync(idOrdenRetiro, nroEnvio)
        End Function
        
        Public Function GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadora(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As String Implements Oca.Oep_TrackingSoap.GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadora
            Return MyBase.Channel.GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadora(idOrdenRetiro, nroEnvio)
        End Function
        
        Public Function GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadoraAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As System.Threading.Tasks.Task(Of String) Implements Oca.Oep_TrackingSoap.GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadoraAsync
            Return MyBase.Channel.GetHtmlDeEtiquetasPorOrdenOrNumeroEnvioParaEtiquetadoraAsync(idOrdenRetiro, nroEnvio)
        End Function
        
        Public Function GetDatosDeEtiquetasPorOrdenOrNumeroEnvio(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String, ByVal isLocker As Boolean) As Oca.Etiqueta() Implements Oca.Oep_TrackingSoap.GetDatosDeEtiquetasPorOrdenOrNumeroEnvio
            Return MyBase.Channel.GetDatosDeEtiquetasPorOrdenOrNumeroEnvio(idOrdenRetiro, nroEnvio, isLocker)
        End Function
        
        Public Function GetDatosDeEtiquetasPorOrdenOrNumeroEnvioAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String, ByVal isLocker As Boolean) As System.Threading.Tasks.Task(Of Oca.Etiqueta()) Implements Oca.Oep_TrackingSoap.GetDatosDeEtiquetasPorOrdenOrNumeroEnvioAsync
            Return MyBase.Channel.GetDatosDeEtiquetasPorOrdenOrNumeroEnvioAsync(idOrdenRetiro, nroEnvio, isLocker)
        End Function
        
        Public Function GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvio(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As String Implements Oca.Oep_TrackingSoap.GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvio
            Return MyBase.Channel.GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvio(idOrdenRetiro, nroEnvio)
        End Function
        
        Public Function GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As System.Threading.Tasks.Task(Of String) Implements Oca.Oep_TrackingSoap.GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioAsync
            Return MyBase.Channel.GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioAsync(idOrdenRetiro, nroEnvio)
        End Function
        
        Public Function GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadora(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As String Implements Oca.Oep_TrackingSoap.GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadora
            Return MyBase.Channel.GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadora(idOrdenRetiro, nroEnvio)
        End Function
        
        Public Function GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadoraAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String) As System.Threading.Tasks.Task(Of String) Implements Oca.Oep_TrackingSoap.GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadoraAsync
            Return MyBase.Channel.GetHtmlDeEtiquetasLockersPorOrdenOrNumeroEnvioParaEtiquetadoraAsync(idOrdenRetiro, nroEnvio)
        End Function
        
        Public Function GetPdfDeEtiquetasPorOrdenOrNumeroEnvio(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String, ByVal logisticaInversa As Boolean) As String Implements Oca.Oep_TrackingSoap.GetPdfDeEtiquetasPorOrdenOrNumeroEnvio
            Return MyBase.Channel.GetPdfDeEtiquetasPorOrdenOrNumeroEnvio(idOrdenRetiro, nroEnvio, logisticaInversa)
        End Function
        
        Public Function GetPdfDeEtiquetasPorOrdenOrNumeroEnvioAsync(ByVal idOrdenRetiro As Integer, ByVal nroEnvio As String, ByVal logisticaInversa As Boolean) As System.Threading.Tasks.Task(Of String) Implements Oca.Oep_TrackingSoap.GetPdfDeEtiquetasPorOrdenOrNumeroEnvioAsync
            Return MyBase.Channel.GetPdfDeEtiquetasPorOrdenOrNumeroEnvioAsync(idOrdenRetiro, nroEnvio, logisticaInversa)
        End Function
    End Class
End Namespace
